name: Setup Ubuntu Desktop and XRDP with Sleep and Fix

on:
  workflow_dispatch:

jobs:
  setup-desktop:
    runs-on: ubuntu-latest

    steps:
    - name: Update apt repositories with release info change allowed
      run: sudo apt-get update --allow-releaseinfo-change

    - name: Fix missing packages and upgrade
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get upgrade --fix-missing -y

    - name: Install ubuntu-desktop
      run: sudo apt install ubuntu-desktop -y

    - name: Install xrdp
      run: sudo apt install xrdp -y

    - name: Set root password
      run: echo "root:123456" | sudo chpasswd

    - name: Get runner public IP
      id: get_ip
      run: |
        IP=$(curl -s https://api.ipify.org)
        echo "Runner IP: $IP"
        echo "::set-output name=ip::$IP"

    - name: Show runner IP
      run: echo "The runner public IP is ${{ steps.get_ip.outputs.ip }}"

    - name: Sleep for 6 hours
      run: sleep 21600s
      shell: bash
